<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
		<!--
		  Make sure any documentation comments which are included in code get checked for syntax during the build, but do
		  not report warnings for missing comments.
    
		  CS1573: Parameter 'parameter' has no matching param tag in the XML comment for 'parameter' (but other parameters do)
		  CS1591: Missing XML comment for publicly visible type or member 'Type_or_Member'
		-->
		<DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
		<NoWarn>$(NoWarn),1573,1591,1712</NoWarn>
	</PropertyGroup>

    <PropertyGroup>
        <!-- Disables the SA1011, SA1200, SA1413 and SA1633 rules from StyleCop -->
        <NoWarn>$(NoWarn),SA1011,SA1200,SA1413,SA1633</NoWarn>
    </PropertyGroup>

    <ItemGroup>
	    <AdditionalFiles Include="..\Stylecop.json">
		    <Link>Stylecop.json</Link>
	    </AdditionalFiles>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>
    
</Project>