<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppProject.Utils\AppProject.Utils.csproj" />
    <ProjectReference Include="..\AppProject.Web.ApiClient.General\AppProject.Web.ApiClient.General.csproj" />
    <ProjectReference Include="..\AppProject.Web.Framework\AppProject.Web.Framework.csproj" />
    <ProjectReference Include="..\AppProject.Web.Models.General\AppProject.Web.Models.General.csproj" />
    <ProjectReference Include="..\AppProject.Web.Shared\AppProject.Web.Shared.csproj" />
  </ItemGroup>

</Project>
